FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder

COPY . /usr/src/ib-sriov-cni

WORKDIR /usr/src/ib-sriov-cni
RUN make clean && \
    make build

FROM registry.ci.openshift.org/ocp/4.7:base
COPY --from=builder /usr/src/ib-sriov-cni/build/ib-sriov /usr/bin/
WORKDIR /

LABEL io.k8s.display-name="InfiniBand SR-IOV CNI"

COPY ./images/entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
