#Originally from https://raw.githubusercontent.com/k8snetworkplumbingwg/sriov-cni/master/.github/workflows/buildtest.yml
name: Go-build-and-test-amd64
on:
    push:
    pull_request:
    schedule:
      - cron: "0 8 * * 0" # every sunday
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      TARGET: amd64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: GOARCH="${TARGET}" make build

      - name: Lint
        run: make lint

      - name: Go test
        run:  make test
